Traceback (most recent call last):
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/nmearl/miniforge3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/nmearl/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

times = np.linspace(0, 10, 1000)
fluxes = square_dip(times, 3, 2)

f, ax = plt.subplots(dpi=150)

ax.plot(times, fluxes, marker='o')
ax.set_xlabel("Time [day]")
ax.set_ylabel("Change in Brightness")
ax.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 11>[0;34m()[0m
[1;32m      9[0m ax[38;5;241m.[39mset_xlabel([38;5;124m"[39m[38;5;124mTime [day][39m[38;5;124m"[39m)
[1;32m     10[0m ax[38;5;241m.[39mset_ylabel([38;5;124m"[39m[38;5;124mChange in Brightness[39m[38;5;124m"[39m)
[0;32m---> 11[0m [43max[49m[38;5;241;43m.[39;49m[43mshow[49m()

[0;31mAttributeError[0m: 'AxesSubplot' object has no attribute 'show'
AttributeError: 'AxesSubplot' object has no attribute 'show'

